name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: BuildPackages
      run: ./build.sh

    - name: Upload release assets
      uses: venstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.RELEASE_TOKEN }}
        file: dist/*.amd64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true


